/* This source code is Copyright (c) Vibrant Media 2001-2009 and forms part of the patented Vibrant Media product "IntelliTXT" (sm). */ 
if('undefined'==typeof $iTXT){var $iTXT={};}if('undefined'==typeof $iTXT.glob){$iTXT.glob={};}$iTXT.glob.itxtRunning=1;if('undefined'==typeof $iTXT.parm){$iTXT.parm={};}if('undefined'==typeof $iTXT.cnst){$iTXT.cnst={ELEMENT_NODE:1,ATTRIBUTE_NODE:2,TEXT_NODE:3,CDATA_SECTION_NODE:4,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11,ADVERTTYPE_INTELLITXTEDIT:0,ADVERTTYPE_LIVEDOTCOM:77,ADVERTTYPE_ZUNE:78}; $iTXT.cnst.ADVERTTYPES_NEW_RENDER=new Array();$iTXT.cnst.ADVERTTYPES_NEW_RENDER['at77'] = true;$iTXT.cnst.ADVERTTYPES_NEW_RENDER['at78'] = true;$iTXT.cnst.ADVERTTYPES_NEW_RENDER['at79'] = true;$iTXT.cnst.ADVERTTYPES_WITH_ICONS=new Array();$iTXT.cnst.ADVERTTYPES_WITH_ICONS['at0']=true;$iTXT.cnst.ADVERTTYPES_WITH_ICONS['at77']=true;} if('undefined'==typeof $iTXT.frnt){$iTXT.frnt={};}$iTXT.frnt.fS=new Date();_qoptions={tags:"526.995.1966"};_qacct="p-fdwEfW0hIeH9U";window.setTimeout('if(itxtLES)itxtLES("http://edge.quantserve.com/quant.js", 100);');
function itxtLES(u){if('string'!=typeof u||!u.match(/^http/)){return;}var e=document.createElement('script');e.src=u;e.type='text/javascript';var b=document.getElementsByTagName('body')[0];b.insertBefore(e, b.firstChild);}
function itxtDSB(u){if('string'!=typeof u||!u.match(/^http/)){return;}try{if(navigator.appVersion.indexOf('MSIE')>=0 && ('complete'!=document.readyState)){document.write('<s'+'cript language="javascript" src="'+u+'"></s'+'cript>');}else itxtLES(u);}catch(e){}};
document.itxtDisabled=1;
if(!document.itxtInProg && document.itxtDisabled){
document.itxtInProg=1;var gSEID=0,gSEST='',gDTmSt=0,gDTmO=0,gQAOL=0;$iTXT.glob.newRender=0;var bvie=navigator.appVersion.indexOf('MSIE')>=0&&navigator.appVersion.indexOf('Opera')<0,gIAS='';
function gTc(name){    var search = name+'=';    var returnvalue = '';    if (document.cookie && (document.cookie.length > 0))    {        offset = document.cookie.indexOf(search);		        if (offset != -1)        		{            offset += search.length;            var end = document.cookie.indexOf(';', offset);            if (end == -1) end = document.cookie.length;            returnvalue=decodeURIComponent(document.cookie.substring(offset, end));        }    }    return returnvalue;}var MUID=gTc('MUID');itxtDSB('http://images.intellitxt.com/ast/js/vm/EventMonitor_9229.js')
if(!$iTXT){var $iTXT={};};if(!$iTXT.core){$iTXT.core={};};if(!$iTXT.data){$iTXT.data={};};if(!$iTXT.fx){$iTXT.fx={};};if(!$iTXT.ui){$iTXT.ui={};};if(!$iTXT.js){$iTXT.js={};};$iTXT.js.load=function(src){if('string'!=typeof src||!src.match(/^http/)){return;}try{var e=document.createElement('script');e.src=src;e.type='text/javascript';var b=document.getElementsByTagName('body')[0];b.insertBefore(e, b.firstChild);}catch(e){}};$iTXT.js.init=function(){};function itxtLoadLibs(){if(navigator.appVersion.indexOf('MSIE')>=0 && 'complete'!=document.readyState){window.setTimeout(itxtLoadLibs, 100);}else{if ($iTXT.js && $iTXT.js.load){$iTXT.js.load('http://images.intellitxt.com/ast/js/vm/jslib/core_9681.js');$iTXT.js.load('http://images.intellitxt.com/ast/js/vm/jslib/data_9692.js');$iTXT.js.load('http://images.intellitxt.com/ast/js/vm/jslib/fx_9557.js');$iTXT.js.load('http://images.intellitxt.com/ast/js/vm/jslib/ui_9493.js');$iTXT.js.check();}}}$iTXT.js.ready=0;$iTXT.js.loader={};$iTXT.js.check=function(){var error=0;if(!$iTXT.js.loader['$iTXT.core.Util']){error=1;}if(!$iTXT.js.loader['$iTXT.core.Builder']){error=1;}if(!$iTXT.js.loader['$iTXT.core.Class']){error=1;}if(!$iTXT.js.loader['$iTXT.core.Event']){error=1;}if(!$iTXT.js.loader['$iTXT.core.Dom']){error=1;}if(!$iTXT.js.loader['$iTXT.data.AdLogger']){error=1;}if(!$iTXT.js.loader['$iTXT.fx.Base']){error=1;}if(!$iTXT.js.loader['$iTXT.fx.Fade']){error=1;}if(!$iTXT.js.loader['$iTXT.fx.Move']){error=1;}if(!$iTXT.js.loader['$iTXT.fx.Queue']){error=1;}if(!$iTXT.js.loader['$iTXT.ui.ComponentBase']){error=1;}if(!$iTXT.js.loader['$iTXT.ui.WindowBase']){error=1;}if(!$iTXT.js.loader['$iTXT.ui.TooltipSlideOut']){error=1;}if(error){window.setTimeout($iTXT.js.check,100);}else{try{$iTXT.core.Util_Load();$iTXT.core.Builder_Load();$iTXT.core.Class_Load();$iTXT.core.Event_Load();$iTXT.core.Dom_Load();$iTXT.data.AdLogger_Load();$iTXT.fx.Base_Load();$iTXT.fx.Fade_Load();$iTXT.fx.Move_Load();$iTXT.fx.Queue_Load();$iTXT.ui.ComponentBase_Load();$iTXT.ui.WindowBase_Load();$iTXT.ui.TooltipSlideOut_Load();}catch(e){}$iTXT.js.ready=1;$iTXT.js.init();if($iTXT.js.onload){$iTXT.js.onload();}}};function itxtBegin(){
var itxturl='http://gamedev.us.intellitxt.com/v3/door.jsp?ts='+(new Date()).getTime()+'&pagecl='+itxtbtl()+'&enc='+itxtGCE()+'&fv='+gDFVS()+'&muid='+MUID+'&ipid=1966&refurl='+document.location.href.replace(/\&/g,'%26').replace(/\'/g, '%27').replace(/\"/g, '%22').replace(/\#(.)*/,'');
itxturl+='&seid='+gSEID+'&sest='+gSEST;
if ($iTXT && $iTXT.js && $iTXT.js.ready) {$iTXT.js.load(itxturl);
} else if ($iTXT && $iTXT.js) {$iTXT.js.onload = function() {
$iTXT.js.load(itxturl);
}
}$iTXT.frnt.fE = new Date();
itxtDSB('http://images.intellitxt.com/ast/js/vm/pmon_9384.js')
}
itxtDSB('http://images.intellitxt.com/ast/js/vm/begin_9655.js');
itxtLoadLibs();
} else {
itxtDSB('http://gamedev.us.intellitxt.com/al.asp?ipid=1966&ts='+(new Date()).getTime()+'&mt=66&mv=0');
}
